
CREATE VIEW [dbo].[Connector - Card Edge]
AS
SELECT        
	PartId,
	Comment,
	Value,
	MfrPartNo AS [Part Number],
	Manufacturer,
	Description,
	Supplier1 AS [Supplier 1],
	Supplier1PartNo AS [Supplier Part Number 1],
	FootprintRef AS [Footprint Ref],
	FootprintPath AS [Footprint Path],
	SymbolRef AS [Library Ref],
	SymbolPath AS [Library Path],
	ComponentLink1Description,
	ComponentLink1URL,
	ComponentLink2Description,
	ComponentLink2URL,
	ComponentLink3Description,
	ComponentLink3URL,
	TemperatureRange AS [Operating Temperature],
	Supplier2 AS [Supplier 2],
	Supplier2PartNo AS [Supplier Part Number 2],
	FootprintRef2 AS [Footprint Ref 2],
	FootprintPath2 AS [Footprint Path 2],
	FootprintRef3 AS [Footprint Ref 3],
	FootprintPath3 AS [Footprint Path 3],
	Price,
	Type,
	Series,

	CardType AS [Card Type],
	Gender,
	NumberOfPositionsBayRow AS [Number of Positions/Bay/Row],
	NumberOfPositions AS [Number of Positions],
	CardThickness AS [Card Thickness],
	NumberOfLevels AS [Number Of Rows],
	Pitch,
	Features,
	MountingType AS [Mounting Type],
	Termination,
	ContactFinish AS [Contact Finish],
	FlangeFeature AS [Flange Feature],
	Colour
FROM            dbo.Components
WHERE        (ComponentType = 'CONN') AND (ComponentSubType = 'CARD')
