


CREATE VIEW [dbo].[Connector - RF]
AS
SELECT        TOP (100) PERCENT PartId,
	Value,
	Comment,
	MfrPartNo AS [Part Number],
	Manufacturer,
	Description,
	Supplier1 AS [Supplier 1],
	Supplier1PartNo AS [Supplier Part Number 1],
	FootprintRef AS [Footprint Ref],
	FootprintPath AS [Footprint Path],
	SymbolRef AS [Library Ref],
	SymbolPath AS [Library Path],
	ComponentLink1Description,
	ComponentLink1URL,
	ComponentLink2Description,
	ComponentLink2URL,
	ComponentLink3Description,
	ComponentLink3URL,
	Supplier2 AS [Supplier 2],
	Supplier2PartNo AS [Supplier Part Number 2],
	FootprintRef2 AS [Footprint Ref 2],
	FootprintPath2 AS [Footprint Path 2],
	FootprintRef3 AS [Footprint Ref 3],
	FootprintPath3 AS [Footprint Path 3],
	Price,
	Type,
	TemperatureRange AS [Operating Temperature],
	Style,
	Series,
	ContactTermination AS [Contact Termination],
	ShieldTermination AS [Shield Termination],
	Impedance,
	MountingType AS [Mounting Type],
	CableGroup AS [Cable Group],
	FasteningType AS [Fastening Type],
	FrequencyUpper AS [Frequency - Max],
	Features,
	Colour AS [Housing Colour],
	IngressProtection AS [Ingress Protection],
	BodyMaterial AS [Body Material],
	BodyFinish AS [Body Finish],
	CenterContactMaterial AS [Center Contact Material],
	CenterContactPlating AS [Center Contact Plating],
	DielectricMaterial AS [Dielectric Material],
	Voltage AS [Voltage Rating]
FROM            dbo.Components
WHERE        (ComponentType = 'CONN') AND ComponentSubType = 'RF'