
CREATE VIEW [dbo].[RF Amplifier]
AS
SELECT        PartId, 
Value, 
Comment, 
MfrPartNo AS [Part Number], 
Manufacturer, 
Description, 
Supplier1 AS [Supplier 1], 
Supplier1PartNo AS [Supplier Part Number 1], 
FootprintRef AS [Footprint Ref], 
FootprintPath AS [Footprint Path], 
SymbolRef AS [Library Ref], 
SymbolPath AS [Library Path], 
ComponentLink1Description, 
ComponentLink1URL, 
ComponentLink2Description, 
ComponentLink2URL, 
ComponentLink3Description, 
ComponentLink3URL, 
Supplier2 AS [Supplier 2], 
Supplier2PartNo AS [Supplier Part Number 2], 
FootprintRef2 AS [Footprint Ref 2], 
FootprintPath2 AS [Footprint Path 2], 
FootprintRef3 AS [Footprint Ref 3], 
FootprintPath3 AS [Footprint Path 3], 
DevicePackage AS [Device Package],
Price, 
Type, 
Series,
TransistorType AS [Transistor Type],
VoltageBreakdown AS [Voltage - Collector Emitter Breakdown (Max)],
Frequency AS [Frequency - Transition],
NoiseFigure AS [Noise Figure (dB Typ @ f)],
Gain,
PowerMax AS [Power - Max],
DcCurrentGain AS [DC Current Gain (hFE)(min) @ Ic, Vce],
CurrentCollector AS [Current - Collector (Ic)(Max)]

FROM            dbo.Components
WHERE        (ComponentType = 'RFIC') AND (ComponentSubType = 'AMP')