


CREATE VIEW [dbo].[Sensor - Magnetic]
AS
SELECT        TOP (100) PERCENT PartId,
	Value,
	Comment,
	MfrPartNo AS [Part Number],
	Manufacturer,
	Description,
	Supplier1 AS [Supplier 1],
	Supplier1PartNo AS [Supplier Part Number 1],
	FootprintRef AS [Footprint Ref],
	FootprintPath AS [Footprint Path],
	SymbolRef AS [Library Ref],
	SymbolPath AS [Library Path],
	ComponentLink1Description,
	ComponentLink1URL,
	ComponentLink2Description,
	ComponentLink2URL,
	ComponentLink3Description,
	ComponentLink3URL,
	Supplier2 AS [Supplier 2],
	Supplier2PartNo AS [Supplier Part Number 2],
	FootprintRef2 AS [Footprint Ref 2],
	FootprintPath2 AS [Footprint Path 2],
	FootprintRef3 AS [Footprint Ref 3],
	FootprintPath3 AS [Footprint Path 3],
	Price,
	Type,
	TemperatureRange AS [Operating Temperature],
	DevicePackage AS [Device Package],
	PartStatus AS [Part Status],
	Features,
	Technology,
	Axis,
	SensingRange AS [Sensing Range],
	Voltage AS [Voltage - Supply],
	CurrentSupply AS [Current - Supply (Max)],
	CurrentOutput AS [Current - Output (Max)],
	OutputType AS [Output Type],
	Resolution,
	Bandwidth
FROM            dbo.Components
WHERE        (ComponentType = 'SENS') AND (ComponentSubType = 'MAG')